.github/workflows.meta
.github/workflows/pr-test-runner.yml

- Added test runner action which checkouts unity-sdk and checkout core repo's branch and run gameCI testrunner on it.
- Validate if test runner is running

[3457539274] Add test runner

---

README.md

-   First pass on ReadMe for Core module 
-   ReadMe.md

[3638377425] Feature/update readme

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CODE_OF_CONDUCT.md
CODE_OF_CONDUCT.md.meta
CONTRIBUTING.md
CONTRIBUTING.md.meta

-   adding contribution guide, issue templates and code of conduct
-   contributing.md (basic contribution guide)
- issue templates (bug report and feature request) 
- code of conduct (copied from GitHub open source docs)
-   Open repo and check files :) 
I used these as repo docs as references
https://github.com/github/docs/blob/main/CONTRIBUTING.md
https://github.com/rails/rails/blob/main/CONTRIBUTING.md
https://github.com/atteneder/glTFast/tree/main/.github/ISSUE_TEMPLATE

[3651634299] Add contribution guide and other docs

---

Editor/Analytics/AmplitudeEventLogger.cs
Editor/EditorAssetGenerator.cs
Editor/Module Management/ModuleInfo.cs
Editor/Module Management/ModuleInstaller.cs
Editor/Module Management/ModuleList.cs
Runtime/ApplicationData.cs
Runtime/Logger/SDKLogger.cs

- Version to ModuleInfo
- Sending of all modules version to amplitude
- Fix PartnerdomainSettings capitalization
- Import the modules in empty project and check amplitude events

[3664834472] Add modules version to analytics

---

Editor/Analytics/AmplitudeEventLogger.cs
Editor/Analytics/AnalyticsEditorLogger.cs
Editor/Analytics/AnalyticsEventLogger.cs
Editor/Analytics/Constants.cs
Editor/Analytics/IAnalyticsEventLogger.cs
Editor/AnalyticsConfirmationEditorWindow.cs
Editor/Banner.cs
Editor/EditorAssetGenerator.cs
Editor/EditorUtilities.cs
Editor/EditorWindowBase.cs
Editor/EntryPoint.cs
Editor/Module Management/ModuleInfo.cs
Editor/Module Management/ModuleInstaller.cs
Editor/Module Management/ModuleList.cs
Editor/Module Management/ModuleUpdater.cs
Editor/SubdomainHelper.cs

-  This is a first pass on adding inline code docs (XML commentation) into the Avatar loader module. 
- I tried to stick to the conventions/practices outline here https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments
-   Inline code docs
-   A number of functions and properties were renamed or refactored.
-  redundant or unused code, parameters and classes.

[3128625539] Feature/inline code docs

---

.github/CODEOWNERS

-   adds a codeowners file to automatically include PR reviewers
-   codeowners file for automatic PR reviewers

[2919913072] Add codeowners for automatic PR reviwers

---

Runtime/Logger/SDKLogger.cs

-   Added setting either enable or disable the RPM logger in RPM Settings window under "Other" section. It uses a "ProjectPref" to keep its state in between sessions.              
-   Logging enabled setting for SDK logger

[3739587991] Feature/optional logging

---

.github/latest.md
.github/workflows/auto-release-action.yml

-   added git action to auto create releases when tag is pushed
-   git action for automatic release creation

[3853039729] feat: added automatic release action

---

Tests/Editor/SDKLoggerTests.cs

-  fixed the tests that were breaking since we added optional SDK logging. 
- 
-   SDK logger tests to handle optional logging

chore: fix logger tests

---

LICENSE.md
package.json

-   Update LICENSE url
-   License URL to reflect new repo name

Update LICENSE url

---

Editor/Module Management/ModuleUpdater.cs

-   a small fix that handles if moduleinfo's branch is empty
-  Module updater to handle empty branch

[3982409503] fix: handle if no branch is set

---

Editor/Module Management/ModuleUpdater.cs

- Added a button in module update prompt, which lets you skip the showing of prompt on project open.
-  Don't ask button in module update prompt
- Test the package in new project, and observe the prompt after selecting don't ask

[3755486782] Add don't ask button module update prompt

---

README.md

- README.md with alternative installation including OpenUPM
- Shield for latest release.
-  NA

[4034599675] Update README.md with OpenUPM installation

---

README.md

- README.md with discussion link
- NA

[4026834296] Add discussion link to readme

---

Editor/Analytics/AmplitudeEventLogger.cs
Runtime/Data/Response.cs
Runtime/Data/Response.cs.meta
Runtime/Data/ResponseFile.cs
Runtime/Data/ResponseFile.cs.meta
Runtime/Data/ResponseTexture.cs
Runtime/Data/ResponseTexture.cs.meta
Runtime/OperationExecutor.cs
Runtime/Utils/IResponse.cs
Runtime/Utils/IResponse.cs.meta
Runtime/Utils/WebRequestDispatcher.cs
Runtime/Utils/WebRequestDispatcher.cs.meta

- WebRequestDispatcher from AvatarLoader
- Made it generalized for any kind of rest request
- Depends on https://github.com/readyplayerme/rpm-unity-sdk-avatar-loader/pull/67
- Test samples and avatar loading using editor
[SDK-79]: https://ready-player-me.atlassian.net/browse/SDK-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-79] Refactor WebRequestDispatcher

---

Runtime/Data/Response.cs
Runtime/Data/ResponseFile.cs
Runtime/Data/ResponseTexture.cs
Runtime/Utils/IResponse.cs
Runtime/Utils/WebRequestDispatcher.cs

- Response code in IResponse 
[SDK-101]: https://ready-player-me.atlassian.net/browse/SDK-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-101] Add response code

---

CONTRIBUTING.md
Editor/Analytics/AmplitudeEventLogger.cs
Editor/Module Management/ModuleInfo.cs
Editor/Module Management/ModuleInstaller.cs
Editor/Module Management/ModuleUpdater.cs
Editor/ReadyPlayerMe.Core.Editor.asmdef
Editor/UI/Components/AnalyticsPanel.cs
Editor/UI/Components/Banner.cs
Editor/UI/Components/Footer.cs
Editor/UI/Components/QuickStartPanel.cs
Editor/UI/EditorWindows/EditorWindowBase.cs
Editor/UI/EditorWindows/WelcomeWindow.cs
Editor/Utils/EntryPoint.cs
Editor/Utils/ProjectPrefs.cs
Runtime/CoreSettingsHandler.cs
Runtime/Data/Response.cs
Runtime/Data/ResponseFile.cs
Runtime/OperationExecutor.cs
Runtime/Utils/WebRequestDispatcher.cs
Tests/Editor/ReadyPlayerMe.Core.Editor.Tests.asmdef
style-guidelines.md
style-guidelines.md.meta

- update style guide links in contributing.md 
- added style-guidelines.md to hold all documentation (and links) to the style guide
- and ran the auto reformat and cleanup with rider C# code style settings applied
-   style-guidelines.md
-  style guide links in contributing.md
[SDK-43]: https://ready-player-me.atlassian.net/browse/SDK-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

[SDK-43] Feature/contribution update

---

.github/workflows.meta
.github/workflows/update-unity-sdk.yml
Tests/Editor/OperationExecutorTests.cs
Tests/Editor/SDKLoggerTests.cs

```Package
Avatar Loader: develop
```
- Github action which runs when PR is merged into develop and updates unity-sdk submodules\
-  None
[SDK-134]: https://ready-player-me.atlassian.net/browse/SDK-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-134] Add action for updating unity-sdk

---

Runtime/Utils/DirectoryUtility.cs

```Package
Avatar Loader: feature/cache-update
```
-   added extra helper functions useful for avatar cache
-  extra helper functions useful for avatar cache

feat: add folder size in MB function

---

Editor/UI/Components/DocumentationButton.cs
Editor/UI/Components/SubdomainField.cs
Runtime/Utils/DirectoryUtility.cs

```Package
Avatar Loader: feature/editor-window-updates
```
-  Some small UI and layout fixes
-  Core settings  window updates
- style updates to help button

small UI fix for docs button and subdomain URL

---

Editor/Module Management/ModuleList.cs
Editor/Utils/EditorUtilities.cs
Runtime/Utils/DirectoryUtility.cs
Runtime/Utils/WebRequestDispatcher.cs

```Package
Avatar Loader: feature/cache-refactor
```
-   some minor changes to complement the avatar cache refactor for avatar loader module. 
-   directory and path logic 
-   saveInProjectFolder function parameter as its no longer needed
[SDK-195]: https://ready-player-me.atlassian.net/browse/SDK-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-195] Feature/cache refactor

---

Editor/Module Management/ModuleUpdater.cs

-  Added removing of avatar loader when modules are updated
- Its very hard to test, I tested it by just adding and running the function in new project which had rpm sdk installed
[SDK-268]: https://ready-player-me.atlassian.net/browse/SDK-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-268] Add removing of avatar loader on update

---

Runtime/Utils/AvatarAPIParameters.cs
Runtime/Utils/AvatarConfigProcessor.cs
Tests/Editor/AvatarConfigProcessorTests.cs
Tests/Editor/AvatarLoaderTests.cs
Tests/Editor/QueryBuilderTests.cs

```Package
Avatar Loader: branch
```
-   pass lod parameter to the avatar loader query instead of meshlod
-   pass lod parameter to the avatar loader query instead of meshlod
- Open up test scene for avatar lod
- When changing distance, the LOD is also applied to the head.
[SDK-259]: https://ready-player-me.atlassian.net/browse/SDK-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-259] change meshlod to lod

---

CHANGELOG.md
Editor/Module Management/ModuleInstaller.cs
Editor/Module Management/ModuleUpdater.cs
Runtime/Analytics/AmplitudeEventLogger.cs
package.json

-   fix for analytics going to wrong environment 

[SDK-332] Hotfix/v3.1.1

---

Tests/Editor/AvatarLoaderTests.cs

-   Fix test Low_LOD_Smaller_than_High_LOD

fix failing test

---

Tests/Editor/AvatarAPITests.cs
Tests/Editor/AvatarLoaderTests.cs

[SDK-348]: https://ready-player-me.atlassian.net/browse/SDK-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-348] Feature/test updates

---

.github/workflows/integration-test.yml
Editor/Module Management/ModuleInstaller.cs
Runtime/AvatarObjectLoader.cs

- Update module installer to work in batch mode
- Add integration test for running core in empty project
-  Import in empty project
[SDK-428]: https://ready-player-me.atlassian.net/browse/SDK-428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-428] Add integration test in an empty project

---

.github/latest.md
CHANGELOG.md
Editor/Module Management/ModuleInstaller.cs
README.md
Runtime/Data/ApplicationData.cs
package.json

-   this PR includes a fix that will make WebView only auto-install on first import, if it is later remove it won't be automatically reimported. 
[SDK-511]: https://ready-player-me.atlassian.net/browse/SDK-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-511] Hotfix/v3.2.4

---

.github/CODEOWNERS
Editor/UI/EditorWindows/SetupGuide/SetupGuide.uxml

- Disable use demo toggle in setup guide
- Run setup guide
[SDK-514]: https://ready-player-me.atlassian.net/browse/SDK-514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-514] Disable use demo toggle in setup guide

---

Runtime/Operations/UrlProcessor.cs
Samples~/AvatarLoadingSamples/AvatarLoading/AvatarLoadingExample.cs
Samples~/AvatarLoadingSamples/AvatarLoading/AvatarLoadingExample.unity
Samples~/AvatarLoadingSamples/AvatarLod/AvatarLodExample.unity
Samples~/AvatarLoadingSamples/MultipleAvatarLoading/MultipleAvatarLoadingExample.cs
Samples~/AvatarLoadingSamples/MultipleAvatarLoading/MultipleAvatarLoadingExample.unity
Samples~/AvatarLoadingSamples/MultipleQualityAvatarLoading/MultipleQualityAvatarLoadingExample.cs
Samples~/AvatarLoadingSamples/MultipleQualityAvatarLoading/MultipleQualityAvatarLoadingExample.unity
Tests/Editor/AvatarAPITests.cs
Tests/Editor/AvatarUriProcessTests.cs

-   Replace API URLs with model URLs for shortcodes
[SDK-472]: https://ready-player-me.atlassian.net/browse/SDK-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: change shortcode to model url

---

Editor/UI/EditorWindows/Templates/AppIdTemplate.cs
Editor/UI/EditorWindows/Templates/SubdomainTemplate.cs
Samples~/AvatarCreatorSamples/Scripts/UI/AvatarCreatorStateMachine.cs

- Updated app id missing error message when avatar creator sample is run
-   Set app id in settings to empty and run avatar creator sample
[SDK-411]: https://ready-player-me.atlassian.net/browse/SDK-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-411] Update app id missing error message

---

CHANGELOG.md
Runtime/GLTF/GltFastGameObjectInstantiator.cs
package.json

-   This PR includes updates to support GLTF 6.0 it is a breaking change and it seems there isn't an elegant way to add or handle backwards compatibility. 
-  Importy gltfast 6.0 and our SDK (this branch) everything should work without errors
[SDK-623]: https://ready-player-me.atlassian.net/browse/SDK-623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-623] feat: update api to work with GLTFast 6.0

---

Editor/UI/EditorWindows/SetupGuide/SetupGuide.cs

-   Tiny PR adding UTM source param to studio url

[SDK-624] feat: add utm source param

---

Runtime/AvatarCreator/Prefabs.meta
Runtime/AvatarCreator/Prefabs/Login Element.prefab
Runtime/AvatarCreator/Prefabs/Login Element.prefab.meta
Runtime/AvatarCreator/UI.meta
Runtime/AvatarCreator/UI/LoginElement.cs
Runtime/AvatarCreator/UI/LoginElement.cs.meta

-   This PR adds a generic Login panel with all the required elements and functionality including a ready to use prefab with events on fail and success
- It also makes it's own request to send verification code and login with code

feat: added basic login element

---

Tests/Editor/AvatarAPITests.cs
Tests/Editor/AvatarLoaderTests.cs
Tests/Editor/AvatarRenderLoaderTests.cs

- Refactor tests by replacing ienumerator to async/await
-  Run the tests
[SDK-591]: https://ready-player-me.atlassian.net/browse/SDK-591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-591] Replace ienumerator with async/await

---

Editor/UI/EditorWindows/IntegrationGuide/IntegrationGuide.cs

-   Dont close integration guide when click quick start
[SDK-661]: https://ready-player-me.atlassian.net/browse/SDK-661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-661] feat: remove close call

---

Editor/UI/EditorWindows/Templates/SubdomainTemplate.cs

-  I'm adding an extra condition to the fix I made in this PR 
https://github.com/readyplayerme/rpm-unity-sdk-core/pull/183
because it without it, the field because difficult to type in due to the constant refocusing 
[SDK-719]: https://ready-player-me.atlassian.net/browse/SDK-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-719] fix: reverted force focus

---

Runtime/AvatarCreator/Scripts/UI/PhotoCaptureElement.cs

- Added fetching of camera permission for ios and android
- Also fixed orientation of captured image
[SDK-593]: https://ready-player-me.atlassian.net/browse/SDK-593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-593] Add permission and orientation fix to photo capture element

---

Runtime/WebView/Data/UrlConfig.cs

-  fixing an issue causing url config tests to fail
[SDK-726]: https://ready-player-me.atlassian.net/browse/SDK-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-726] chore: fix for failing url tests

---

Editor/Core/Scripts/Module Management/ModuleList.cs

-   smol PR updating draco version
-   install in a test project and see that using draco still works and there are no breaking API changes
[SDK-731]: https://ready-player-me.atlassian.net/browse/SDK-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-731] Feature/update draco

---

Editor/Core/Scripts/ModuleManagement/ModuleInstaller.cs
Editor/Core/Scripts/ModuleManagement/ModuleList.cs

-   Remove the Webview package installation from the core
-   Import the core package and observe, that the Webview is not installed anymore.
[SDK-744]: https://ready-player-me.atlassian.net/browse/SDK-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-744] - Remove webview from the core

---

Runtime/WebView/WebViewEvents.cs
Samples~/WebGLSample/Scripts/WebFrameHandler.cs

feat: add new iframe events to the sdk

---

Runtime/AvatarCreator/Prefabs/Elements/LogoutElement.prefab
Runtime/AvatarCreator/Prefabs/Elements/LogoutElement.prefab.meta
Runtime/AvatarCreator/Scripts/UI/Elements/LogoutElement.cs
Runtime/AvatarCreator/Scripts/UI/Elements/LogoutElement.cs.meta
Samples~/AvatarCreatorSamples/AvatarCreatorExperimental/README.md

-   Add logout element
-   Add login element and after click on logout button, and observe, that the user is logged out
[SDK-783]: https://ready-player-me.atlassian.net/browse/SDK-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add logout element

---

Runtime/AvatarCreator/Scripts/UI/Elements/SelectionElement.cs

-   Recover hair, when headwear is selected
-   Test in experimental scene, that this works correctly
[SDK-777]: https://ready-player-me.atlassian.net/browse/SDK-777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: recover hair, when headwear is not selected

---

Samples~/AvatarCreatorSamples/AvatarCreatorElements/Scripts/SimpleAvatarCreator.cs

-   Update gender, when the avatar has been loaded.
-   create the template of male and female avatars.
[SDK-830]: https://ready-player-me.atlassian.net/browse/SDK-830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update gender, when avatar has been updated

---

CHANGELOG.md
Runtime/Core/Scripts/Data/ApplicationData.cs
Samples~/AvatarCreatorSamples/AvatarCreatorWizard/Scripts/UI/SelectionScreens/CameraPhotoSelection.cs
package.json

-   Fix issue, where you can't edit avatar done with the photo
-   Make a photo and check, that you can edit the avatar
[SDK-883]: https://ready-player-me.atlassian.net/browse/SDK-883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: fix issue with picture of avatar not being editable

---

Editor/Core/Scripts/Analytics/Constants.cs
Editor/Core/Scripts/UI/EditorWindows/Templates/Resources/AvatarUrlTemplate.uxml
Editor/Core/Scripts/UI/EditorWindows/Templates/SubdomainTemplate.cs
Runtime/AvatarCreator/Scripts/UI/Elements/PhotoCaptureElement.cs
Samples~/AvatarCreatorSamples/AvatarCreatorElements/Scenes/AvatarCreatorElements.unity
Samples~/AvatarCreatorSamples/AvatarCreatorWizard/Scripts/UI/SelectionScreens/CameraPhotoSelection.cs

-   updated avatar loader link
- added conditional define symbol to prevent auto camera permissions for android (useful for quest app submissions) it hides any use of WebCamTexture all they need to do is add RPM_DISABLE_CAMERA_PERMISSION to define symbols for android (or whatever other platform they want to disable for). 
I also made a separate task to clean this up later by isolating the camera logic
https://ready-player-me.atlassian.net/browse/SDK-909?atlOrigin=eyJpIjoiNDI4MGM5NTNkOGNjNGU1NmJhZTY1ZDg3MzI1NzhlYzIiLCJwIjoiaiJ9
[SDK-742]: https://ready-player-me.atlassian.net/browse/SDK-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

[SDK-742] Feature/bug fixes

---

.github/latest.md
CHANGELOG.md
Runtime/AvatarCreator/Scripts/Managers/AvatarManager.cs
Runtime/Core/Scripts/Data/ApplicationData.cs
package.json

-   in 6.2.0 there was an issue with the new CreateAvatarFromTemplateAsync method that it didn't set gender and avatarID

hotfix for avatar templates method

---

.github/latest.md
CHANGELOG.md
Runtime/Core/Scripts/Data/ApplicationData.cs
Runtime/Core/Scripts/Extensions/ExtensionMethods.cs
package.json

-  reverted update to GetMeshRenderer method to fix mesh transfer issues

chore: revert update to GetMeshRendererMethod

---

Runtime/AvatarCreator/Scripts/Data/PartnerAsset.cs

Content from API includes this field, but the Unity code does not.

Add Locked field to PartnerAsset.cs

---

Runtime/AvatarCreator/Scripts/Managers/AuthManager.cs
Runtime/Core/Scripts/Utils/WebRequestDispatcher.cs
Samples~/AvatarCreatorSamples/AvatarCreatorWizard/Scripts/UI/SelectionScreens/AvatarCreatorSelection.cs

-   This fixes an issue caused by calling the AuthManager.Signup multiple times. It was being called from both AvatarCreatorSelection & on the SignUpElement, resulting in 2 requests. 
- this should fix [this issue](https://ready-player-me.atlassian.net/browse/SDK-901?atlOrigin=eyJpIjoiZjVmZDlkZjg4MTk1NDRmZDlmMDMxOGRjYTYzNGVhYjciLCJwIjoiaiJ9) 
[SDK-901]: https://ready-player-me.atlassian.net/browse/SDK-901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-901] Feature/wizard signup fix

---

Editor/Core/Scripts/Analytics/Constants.cs
Editor/Core/Scripts/UI/EditorWindows/Templates/AvatarUrlTemplate.cs

-   Update avatar loader window help link to use the correct docs page
[SDK-959]: https://ready-player-me.atlassian.net/browse/SDK-959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update avatar loader window url

---

Runtime/AvatarCreator/Scripts/InCreatorAvatarLoader.cs
Runtime/AvatarCreator/Scripts/Managers/AvatarManager.cs

-   This PR fixes an issue that avatar config is not being applied to InCreatorLoader 
[SDK-979]: https://ready-player-me.atlassian.net/browse/SDK-979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-979] fix: added avatar config to InCreatorLoader

---

.github/workflows/pr-test-runner.yml
Runtime/AvatarCreator/Scripts/Managers/AvatarManager.cs
Runtime/AvatarCreator/Scripts/UI/Elements/BodyShapeSelectionElement.cs
Runtime/AvatarCreator/Scripts/WebRequests/AvatarAPIRequests.cs
Runtime/Core/Scripts/Extensions/EnumExtensions.cs
Runtime/Core/Scripts/JsonConverters/BodyTypeConverter.cs

-   Fetch body type specific templates
-   Verify, that correct templates are selected
[SDK-980]: https://ready-player-me.atlassian.net/browse/SDK-980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-980] fetch bodytype specific templates

---

Editor/Core/Scripts/UI/EditorWindows/AvatarLoaderEditor/AvatarLoaderEditor.cs

-   Fix avatar loading view buttons
[SDK-958]: https://ready-player-me.atlassian.net/browse/SDK-958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: fix invalid loading settings

---

Samples~/AvatarCreatorSamples/AvatarCreatorWizard/Scripts/UI/AvatarCreatorStateMachine.cs
Samples~/AvatarCreatorSamples/AvatarCreatorWizard/Scripts/UI/SelectionScreens/AvatarCreatorSelection.cs

-   Allow going back after login
[SDK-994]: https://ready-player-me.atlassian.net/browse/SDK-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-994] feat: go back after login

---

.github/latest.md
CHANGELOG.md
Runtime/Core/Scripts/Data/ApplicationData.cs
Runtime/WebView/Data/WebMessage.cs
Runtime/WebView/WebMessageHelper.cs
package.json

-   This PR includes a change to improve the handling of iFrame events and prevent json conversion isues

fix: update web message json handling

---

Runtime/AvatarCreator/Scripts/Data/Constants/AuthConstants.cs
Runtime/AvatarCreator/Scripts/Data/CreatedUser.cs
Runtime/AvatarCreator/Scripts/Data/UserSession.cs
Runtime/AvatarCreator/Scripts/JsonConverters/AuthDataConverter.cs
Runtime/AvatarCreator/Scripts/WebRequests/AuthAPIRequests.cs
Runtime/AvatarCreator/Scripts/WebRequests/AvatarAPIRequests.cs
Samples~/AvatarCreatorSamples/AvatarCreatorWizard/Scripts/UI/SelectionScreens/AvatarCreatorSelection.cs

-   Switched from old authentication endpoints to the new ones in auth-service
-   Use the Avatar Creator Wizard functionality and verify it works:
-   Log in with email code
-   Sign up when clicking Next in the editor
[AUTH-6]: https://ready-player-me.atlassian.net/browse/AUTH-6?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AUTH-6] Use auth-service endpoints for auth-related requests

---

Runtime/Core/Scripts/Data/AvatarData.cs

Avatar Destroy
