Configurations/Avatar Config Low.asset
Configurations/Avatar Config Medium.asset
Runtime/Data/ReadyPlayerMeSettings.cs

Fixed null exception when loading instance of settings through settings asset.
Verify if there is no null exception while opening settings window

fix null exception when loading settings

---

Runtime/CoreSettingsHandler.cs

-  there is currently a number of issues  cause if the core settings asset is not there (or has been deleted) this update fixed that and forces it to be created if it does not exist. 
-   CoreSettingsHandler now creates core settings if missing

fix: force create new settings asset

---

Editor/Analytics/AnalyticsEventLogger.cs
Editor/Analytics/Constants.cs
Editor/Analytics/IAnalyticsEventLogger.cs
Runtime/OperationExecutor.cs

- Extended OperationExecutor with extra event and added new events for analytics.
- OperationCompleted event to OperationExecutor
- Event name constants and functions for avatar loaded and metadata downloaded
- Should be tested with `feature/avatar-loaded-events` branch of avatar loader module
- Try loading avatar from editor window and observe analytics event on amplitude
- Note: analytics should be enabled

[4026673868] Add operation completed event

---

Editor/UI/Components/AnalyticsPanel.cs

-   Small fix that sets don't ask again correctly based on Popup buttons
-   Fix for analytics/welcome popup showing up every time even after enabling 
Scenario 1
-  import into new project, once analytics (welcome) window pops up click enable 
- now if you close the project and reopen it should NOT show again
Scenario 2
- import into new project
- When window pops up click dont enable
- restart unity and it should show again
Scenario 3
- import
- click Dont Ask Again toggle (set to true)
- Click don't enable
- next time you launch it should NOT show 
-   If …

[] Welcome popup fix

---

Editor/Module Management/ModuleInstaller.cs

```Package
Avatar Loader: develop
```
-   adds a timeout to the module installer to prevent importer getting stuck
-   timeout to the module installer to prevent importer getting stuck
-   You can try importing our package and then immediately turning off wifi/internet connection although this may not actually trigger the timeout, but instead request errors 
[SDK-145]: https://ready-player-me.atlassian.net/browse/SDK-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …

SDK-145 chore: added timeout

---

Editor/Module Management/ModuleInstaller.cs
Editor/Module Management/ModuleList.cs
Editor/Utils/ProjectPrefs.cs

```Package
Avatar Loader: feature/setup-guide-fix
```
-   This PR includes some changes to the module installer so that it resets the avatar loader setup guide project pref to ensure the setup guide is displayed whenever avatar loader package is downloaded/ redownloaded
- also includes some refactoring of project prefs script 
-   added logic to module installer reset setup guide project pref
to test, open a project and
-  add this git URL to package manager https://github.com/readyplayerme/rpm-unity-sdk-core.git#feature/setup-guide-fix 
- go through the setup guide
- then delete/remove the RPM packages
- Then re-add core from above URL 
- it should display the setup guide again the fix works correctly
- …

[SDK-185] Feature/setup guide fix

---

.github/latest.md
Editor/Module Management/ModuleList.cs
Editor/Utils/EntryPoint.cs
package.json

```Package
Avatar Loader: hotfix/1.3.4
```
-   This change includes a fix for an issue that caused the log project open and identify user events being fired every time unity recompiles
-   List your additions and new features here.
-   List your updates and changes here.
-   List what is removed here.

[SDK-219] fix: move open project event logic

---

Editor/UI/EditorWindows/SettingsWindow/SettingsEditor.cs
Editor/UI/EditorWindows/SettingsWindow/SettingsEditorWindow.uxml
Editor/UI/EditorWindows/Templates/AppIdTemplate.cs
Editor/UI/EditorWindows/Templates/AppIdTemplate.cs.meta
Editor/UI/EditorWindows/Templates/Resources/AppIdTemplate.uxml
Editor/UI/EditorWindows/Templates/Resources/AppIdTemplate.uxml.meta
Runtime/CoreSettingsHandler.cs
Runtime/Data/CoreSettings.cs
Runtime/Utils/WebRequestDispatcher.cs

- Added app id in core settings and settings window
- App id is sent as header with all requests made from sdk
- Try to check if sent request contains the header
[SDK-305]: https://ready-player-me.atlassian.net/browse/SDK-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-305] Add app id to all web requests

---

Editor/Module Management/ModuleInstaller.cs
Editor/UI/EditorWindows/AvatarLoaderEditor/AvatarLoaderEditor.cs
Editor/UI/EditorWindows/SetupGuide/OneTimeSetup.cs

-   This PR adds a fix for handling an issue where GLTFAST symbol is not recognized after being added. 
Please test on a new FRESH project by importing from this URL 
`https://github.com/readyplayerme/rpm-unity-sdk-core.git#feature/gtlfast-symbol-fix`
-   create new Unity project with unique project name and import package from this branch 
`https://github.com/readyplayerme/rpm-unity-sdk-core.git#feature/gtlfast-symbol-fix`
Then try to immediately load an avatar from Avatar Loader window
[SDK-321]: https://ready-player-me.atlassian.net/browse/SDK-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-321] Feature/gtlfast symbol fix

---

CHANGELOG.md
Editor/UI/EditorWindows/AvatarLoaderEditor/AvatarLoaderEditor.cs
Editor/Utils/EditorUtilities.cs
Runtime/AvatarObjectLoader.cs
package.json

-   there is currently an issue that when a prefab is created during the process of loading an avatar from Avatar Loader window all the mesh and material references are lost. They are applied to object in the scene but are not applied to the prefab (it seems a unity bug/limitation. 
https://forum.unity.com/threads/not-able-to-prefab-meshes-created-through-script.1302210/
[SDK-380]: https://ready-player-me.atlassian.net/browse/SDK-380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: rework prefab creation logic

---

Editor/Utils/EditorUtilities.cs
Tests/Editor/AvatarLoaderWindowTests.cs
Tests/Editor/AvatarLoaderWindowTests.cs.meta
Tests/Editor/Common/TestUtils.cs
Tests/Editor/ReadyPlayerMe.Core.Editor.Tests.asmdef

-   add test to verify, that the prefab created is a directly linked to object in world without overrides or changes.
[SDK-381]: https://ready-player-me.atlassian.net/browse/SDK-381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-381] add test for avatar loader window

---

Editor/UI/EditorWindows/SetupGuide/SetupGuide.cs
Editor/UI/EditorWindows/Templates/SubdomainTemplate.cs
Editor/UI/Obsolete/Components/SubdomainField.cs
Runtime/CoreSettingsHandler.cs

- this PR includes changes to the setup guide window. It will now default to an empty subdomain field and prevent clicking next unless they enter subdomain OR click the "I don't have an account..." toggle instead
- if users close this window without doing anything it will be in the same state next open (still empty)
- conversely if you do enable the "I don't have an account.." toggle it will remember that next time you open the window. 
-   Import the branch in a new project and observe the setup guide popup
- Subdomain field should be empty and display error icon next to it
- next button should be disabled (preventing progression to next screen)
- the "I don't have an account..." toggle should be unchecked by default
- If you close the window without doing anything else it should be in …

[SDK-425] feat: display empty subdomain on quick start

---

Editor/Module Management/ModuleList.cs
Editor/WebView.meta
Editor/WebView/WebViewBuildPostprocessor.cs
Editor/WebView/WebViewBuildPostprocessor.cs.meta
Editor/WebView/WebViewEditor.cs
Editor/WebView/WebViewEditor.cs.meta
Runtime/WebView.meta
Runtime/WebView/Data.meta
Runtime/WebView/Data/Enums.cs
Runtime/WebView/Data/Enums.cs.meta
Runtime/WebView/Data/ScreenPadding.cs
Runtime/WebView/Data/ScreenPadding.cs.meta
Runtime/WebView/Data/UrlConfig.cs
Runtime/WebView/Data/UrlConfig.cs.meta
Runtime/WebView/Data/WebMessage.cs
Runtime/WebView/Data/WebMessage.cs.meta
Runtime/WebView/MessagePanel.cs
Runtime/WebView/MessagePanel.cs.meta
Runtime/WebView/WebMessageHelper.cs
Runtime/WebView/WebMessageHelper.cs.meta
Runtime/WebView/WebViewEvents.cs
Runtime/WebView/WebViewEvents.cs.meta
Samples~/WebGLExample/Scripts/WebFrameHandler.cs
Samples~/WebGLExample/Scripts/WebInterface.cs
Tests/Editor/UrlConfigTests.cs
Tests/Editor/UrlConfigTests.cs.meta

-   moved all data types and classes that can be used universally for any iFrame or integration (including webGL builds) 
- this is linked to this PR for WebView https://github.com/readyplayerme/rpm-unity-sdk-webview/pull/21
-   import this branch in a fresh project or checking out Unity SDK
- NOTE: to prevent errors you will also need to checkout/import the feature branch for webview that also includes these changes `feature/extract-shared-functionality`
- also test the Core WebGL example as that uses some of these classes
[SDK-414]: https://ready-player-me.atlassian.net/browse/SDK-414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[SDK-414]Feature/extract webview logic

---

Editor/Module Management/ModuleUpdater.cs
Editor/UI/EditorWindows/AvatarLoaderEditor/AvatarLoaderEditor.cs
Editor/UI/EditorWindows/IntegrationGuide/IntegrationGuide.cs
Editor/UI/EditorWindows/SetupGuide/SetupGuide.cs

-  update menu item priority for better separation
- also moved the Unity-SDK only menu items (internal dev functions) into a separate RPM Tools section. This enables us to cleanup Ready Player Me section and also see exactly what developers would see after importing the package into a project
[SDK-544]: https://ready-player-me.atlassian.net/browse/SDK-544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-544] feat: update context menu ordering to add separators

---

Editor/Module Management/ModuleInstaller.cs
Editor/UI/EditorWindows/AvatarLoaderEditor/AvatarLoaderEditor.cs
Editor/Utils/DefineSymbolHelper.cs
Editor/Utils/DefineSymbolHelper.cs.meta

-   remove define symbols when core is removed via package manager
- refactor define symbol edit logic into separate class
-   import this branch of core into fresh project
- after import check that define symbols GLTFAST and READY_PLAYER_ME exist
- then remove core via package manager
- check that define symbols are removed. 
[SDK-558]: https://ready-player-me.atlassian.net/browse/SDK-558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-558] feat: refactored symbol edit logic and added symbol remove logic

---

Documentation~/AvatarCreatorSample.md
Documentation~/CustomizationGuide.md.meta
Documentation~/QuickStart.md
Documentation~/QuickStart.md.meta
README.md

-  Updated docs for avatar creator
- Check docs
[SDK-564]: https://ready-player-me.atlassian.net/browse/SDK-564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-564] Update avatar creator docs

---

Editor/UI/EditorWindows/SetupGuide/SetupGuide.cs
Editor/UI/EditorWindows/SetupGuide/SetupGuide.uxml
Editor/UI/EditorWindows/Templates/AppIdTemplate.cs
Editor/UI/EditorWindows/Templates/Resources/AppIdTemplate.uxml

- Added app id to setup guide
-  Import package and open setup guide
[SDK-513]: https://ready-player-me.atlassian.net/browse/SDK-513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-513] Add appid to setup guide

---

Editor/Module Management/ModuleInstaller.cs
Editor/Module Management/ModuleList.cs
Editor/ShaderVariantHelper.cs
Editor/UI/EditorWindows/AvatarLoaderEditor/AvatarLoaderEditor.cs
Editor/Utils/DefineSymbolHelper.cs
Runtime/GLTF/GLTFDeferAgent.cs
Runtime/GLTF/GltFastGameObjectInstantiator.cs
Runtime/GLTF/GltfImporter.cs
package.json

-   Gltfast can now be added by package name and set as a dependency (not using git repository). As such we no longer need to force install it ourselves which will also help us improve the install process.
-   install RPM core as before by git URL (this branch) and observe behaviour but everything should work
[SDK-622]: https://ready-player-me.atlassian.net/browse/SDK-622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-622] Feature/unity gltfast

---

Samples~/WebGLSample/Editor/EditorWindows/SampleSetup.cs

-   Reworks how the auto setup functionality works when importing webGL sample as WebGLHelper also must be in Assets/Plugins folder to work. 
- So this PR adds the auto moving of this folder
- It also moves the folder rather than copies. This is better as you don't end up with file duplicates and that not only bloats the project but causes issues with duplicate GUIDs 
-  import on new projet with this https://github.com/readyplayerme/rpm-unity-sdk-core.git#feature/webgl-helper-update and then import the WebGLSample and click yes and observe behavior 
[SDK-626]: https://ready-player-me.atlassian.net/browse/SDK-626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …

[SDK-626] Feature/webgl helper update

---

Editor/UI/EditorWindows/Templates/SubdomainTemplate.cs

-   now when you paste subdomain `https://kangarudev.readyplayer.me?frameApi` into subdomain field it will correctly resize the text field so that the subdomain is visible. 
[SDK-704]: https://ready-player-me.atlassian.net/browse/SDK-704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-704] feat: fix pasted text display issue

---

Runtime/WebView/Data/UrlConfig.cs
Tests/Editor/UrlConfigTests.cs

-   Add source parameter to the URLs
-   Check, that the event is sent to amplitude with the given source, when opening the avatar creator
[SDK-677]: https://ready-player-me.atlassian.net/browse/SDK-677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add source param to web avatar creator

---

Samples~/AvatarCreatorSamples/LegacyAvatarCreator/Scripts/UI/CategoryUICreator.cs
Samples~/AvatarCreatorSamples/LegacyAvatarCreator/Scripts/UI/PanelSwitcher.cs

- Added clear functionality in panel switcher, which will be called onDestroy
- Try to Load scene twice from a different scene
[SDK-721]: https://ready-player-me.atlassian.net/browse/SDK-721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-721] Add clearing of panel switcher

---

Editor/Core/Scripts/UI/EditorWindows/IntegrationGuide/IntegrationGuide.cs

[SDK-727]: https://ready-player-me.atlassian.net/browse/SDK-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-727] feat: handle loading sample if installed in assets folder

---

Runtime/AvatarCreator/Scripts/Data/AvatarProperties.cs
Runtime/AvatarCreator/Scripts/Managers/AvatarManager.cs
Runtime/Core/Scripts/Utils/WebRequestDispatcher.cs
Samples~/AvatarCreatorSamples/LegacyAvatarCreator/Scripts/UI/SelectionScreens/AvatarCreatorSelection.cs

-  When there is no draft avatar, then don't save the avatar.
-   Try to go over the old avatar creator with an update on the avatar (change some assets) and without changing and verify, that the avatar is successfully loaded in both cases.
[SDK-401]: https://ready-player-me.atlassian.net/browse/SDK-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: don't save, when avatar is not in draft

---

Runtime/Core/Scripts/CommonHeaders.cs

-   Add rpm-source header to the requests. This is used to track the usage of avatar creator.
-   Right now save draft endpoint processes this data. Check, that if you save the draft in the avatar creator, that in amplitude, there will be one extra entry. (This is cached for 12 hours, so you can make only one request)
[SDK-627]: https://ready-player-me.atlassian.net/browse/SDK-627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add rpm-source header to the requests

---

Runtime/AvatarCreator/Scripts/Managers/AvatarManager.cs
Runtime/AvatarCreator/Scripts/UI/Elements/AssetSelectionElement.cs
Runtime/AvatarCreator/Scripts/UI/Elements/SelectionElement.cs
Runtime/AvatarCreator/Scripts/WebRequests/AvatarAPIRequests.cs
Samples~/AvatarCreatorSamples/AvatarCreatorExperimental/Scenes/AvatarCreatorExperimental.unity
Samples~/AvatarCreatorSamples/AvatarCreatorExperimental/Scripts/SimpleAvatarCreator.cs

-   Added default asset selection for template avatars
NOTE this only works for some assets, it doesn't work for outfits which is the same in web 
-   Run the Simple Avatar craetor (Avatar Creator Experimental) and check that after initial load the hair and eyebrows are selected already 
[SDK-776]: https://ready-player-me.atlassian.net/browse/SDK-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-776] Feature/default asset selection

---

Runtime/AvatarCreator/Prefabs/Buttons/ButtonElement.prefab
Runtime/AvatarCreator/Prefabs/Elements/AssetSelectionElement.prefab
Runtime/AvatarCreator/Prefabs/Elements/ColorSelectionElement.prefab
Runtime/AvatarCreator/Prefabs/Elements/TemplateSelectionElement.prefab
Runtime/AvatarCreator/Scripts/Extensions/RawImageExtensions.cs
Runtime/AvatarCreator/Scripts/UI/Buttons/SelectionButton.cs
Runtime/AvatarCreator/Scripts/UI/Elements/SelectionElement.cs
Runtime/AvatarCreator/Scripts/UI/Elements/TemplateSelectionElement.cs

-   small fix for button icon resizing edgecase
- some other minor improvements 
-   test by running the experimental cac example
- to test the default avatar icons you'll need to add it to the scene and call the setup/loading functions manually 
[SDK-789]: https://ready-player-me.atlassian.net/browse/SDK-789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-789] Small fix and minor improvements

---

Runtime/AvatarCreator/Scripts/Managers/AvatarManager.cs
Samples~/AvatarCreatorSamples/AvatarCreatorWizard/Scripts/UI/SelectionScreens/AvatarCreatorSelection.cs

-   Delete the draft avatar, if it exists before editing
- Log into your RPM account  
- Click on the Configure in the avatar in the avatar creator, edit something, and close the play mode
- play again
- Check, that when customizing the avatar, the previous changes are not visible.
[SDK-182]: https://ready-player-me.atlassian.net/browse/SDK-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: delete draft avatar, when the new avatar is loaded for update

---

Samples~/AvatarCreatorSamples/AvatarCreatorExperimental/Prefabs.meta
Samples~/AvatarCreatorSamples/AvatarCreatorExperimental/Prefabs/UserAvatarElement.prefab
Samples~/AvatarCreatorSamples/AvatarCreatorExperimental/Prefabs/UserAvatarElement.prefab.meta
Samples~/AvatarCreatorSamples/AvatarCreatorExperimental/Scenes/AvatarCreatorExperimental.unity
Samples~/AvatarCreatorSamples/AvatarCreatorExperimental/Scripts/SimpleAvatarCreator.cs

-   Update the avatar creator scene, so that you can log in/log out, and create and save new avatars from the template.
-   Verify, that everything works
[SDK-683]: https://ready-player-me.atlassian.net/browse/SDK-683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update avatar creator simple scene to contain user management, create, and save avatar functionality

---

Editor/Core/Scripts/Settings/CoreSettingsLoader.cs

-   this update fixes an issue causing core settings to be overwritten sometimes when the project is reopened. 
[SDK-819]: https://ready-player-me.atlassian.net/browse/SDK-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-819] Feature/core settings fix

---

CHANGELOG.md
Runtime/Core/Scripts/Utils/AvatarMeshHelper.cs

-   Mesh helper now supports transfer from multiple source mesh, material and bones target
-   Load atlassed and non-atlassed avatars with different customization combinations in Photon Sample project
-   [x] Changelog is updated.
[SDK-524]: https://ready-player-me.atlassian.net/browse/SDK-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mesh Helper multi-mesh support

---

CHANGELOG.md
Runtime/Core/Scripts/Utils/AvatarMeshHelper.cs
Tests/Editor/AvatarRenderLoaderTests.cs

- GetHeadMeshes method helps developers get the list of game objects that are related to avatars head, which can be useful for hiding these in certain situations.
- Removed logic for removing unused meshes to avoid missing customizations upon next use.
-   Load a non-atlassed avatar and call the method avatar as it's only parameter.
-   [x] Changelog is updated.

GetHeadMeshes method

---

Runtime/AvatarCreator/Scripts/Managers/AuthManager.cs

These methods could previously fail silently.

Wrap some calls in try/catch in AuthManager.cs

---

Runtime/AvatarCreator/Scripts/UI/Elements/AssetSelectionElement.cs
Runtime/Core/Scripts/Animation/EyeAnimationHandler.cs

-   Remove race condition, when assetSelectionElement is disabled, but it is initialized before it is enabled.
-   When assetSelectionElement is disabled, you can still load the buttons.
[SDK-934]: https://ready-player-me.atlassian.net/browse/SDK-934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-934] - initialize request in property

---

Runtime/AvatarCreator/Scripts/AvatarTemplateFetcher.cs
Runtime/AvatarCreator/Scripts/UI/Elements/TemplateSelectionElement.cs

-   Add option to filter template elements by gender
-   Check, that filtering works for gender
[SDK-797]: https://ready-player-me.atlassian.net/browse/SDK-797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add gender option to template selection element

---

Runtime/AvatarCreator/Scripts/WebRequests/AvatarAPIRequests.cs

-   Throw error before request, if the avatar ID is invalid
-   Try making a request with ID, that is null or empty and see, that it fails with an error
[SDK-778]: https://ready-player-me.atlassian.net/browse/SDK-778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: validate avatar id with requests

---

Runtime/AvatarCreator/Scripts/Managers/AvatarManager.cs

-   Throw error, when body shapes are not enabled in the studio
- Enable body shapes in the studio and test, that shapes are applied and that no error is thrown
- Disable body shapes in the studio and verify, that error is shown and avatar is not updated
[SDK-907]: https://ready-player-me.atlassian.net/browse/SDK-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: log error, when bodyshapes are not enabled in studio

---

Editor/Core/Scripts/UI/EditorWindows/SettingsWindow/SettingsEditor.cs
Editor/Core/Scripts/UI/EditorWindows/SettingsWindow/SettingsEditorWindow.uxml

-   replaced Discord button with forums button + updated link
-   open settings window and check buttons 
[SDK-975]: https://ready-player-me.atlassian.net/browse/SDK-975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-975] feat: replaced discord button and link with forum

---

Samples~/AvatarCreatorSamples/AvatarCreatorElements/Scenes/AvatarCreatorElements.unity
Samples~/AvatarCreatorSamples/AvatarCreatorElements/Scripts/AvatarHandler.cs
Samples~/AvatarCreatorSamples/AvatarCreatorElements/Scripts/AvatarHandler.cs.meta
Samples~/AvatarCreatorSamples/AvatarCreatorElements/Scripts/SessionHandler.cs
Samples~/AvatarCreatorSamples/AvatarCreatorElements/Scripts/SimpleAvatarCreator.cs

-   Refactor avatar creator elements scene and separate avatar management from simple avatar creator script
[SDK-968]: https://ready-player-me.atlassian.net/browse/SDK-968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: refactor avatar creator scene

---

CHANGELOG.md
Editor/Core/Scripts/UI/CustomEditors/AvatarConfigEditor.cs
Runtime/Core/Scripts/Data/ApplicationData.cs
Runtime/Core/Scripts/JsonConverters/BodyTypeConverter.cs
package.json

-   Previous versions stored the body type as an integer. This is fixed, so that they can be now loaded as an integer.
-   Save the avatar in the cache in version 5.0.0 for example, then update SDK to the latest and verify, that the avatars can be still loaded.

fix: allow cache to be loaded from previous versions, where bodyType was stored as an integer

---

Runtime/Core/Scripts/Utils/AvatarMeshHelper.cs

fix: add bones, if bones are not set

---

Runtime/AvatarCreator/Scripts/Interfaces/IAssetData.cs

[SRV-1333](https://ready-player-me.atlassian.net/browse/SRV-1333)
-   Preserve the Id from the IAsset interface, so when stripped in mobile it does not remove it
-   Build a sdk version for android using stripping level high, try to run it in the android emulator
[SRV-1333]: https://ready-player-me.atlassian.net/browse/SRV-1333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: preserve property Id from asset data

---

Runtime/AvatarCreator/Scripts/Extensions/ResponseExtensions.cs
Runtime/AvatarCreator/Scripts/WebRequests/AssetAPIRequests.cs
Runtime/AvatarCreator/Scripts/WebRequests/AuthAPIRequests.cs
Runtime/AvatarCreator/Scripts/WebRequests/AvatarAPIRequests.cs
Runtime/Core/Scripts/Analytics/AmplitudeEventLogger.cs
Runtime/Core/Scripts/Data/Response.cs.meta
Runtime/Core/Scripts/Data/ResponseData.cs
Runtime/Core/Scripts/Data/ResponseData.cs.meta
Runtime/Core/Scripts/Data/ResponseText.cs
Runtime/Core/Scripts/Data/ResponseText.cs.meta
Runtime/Core/Scripts/Extensions/WebRequestDispatcherExtension.cs
Runtime/Core/Scripts/Operations/AvatarDownloader.cs
Runtime/Core/Scripts/Operations/MetadataDownloader.cs

There is an issue with avatar loader when cache is disabled this is meant to fix it by avoiding the call to downloadHandler.Text when attempting to push it.
-  Attempt to load avatar with caching disable and observe a spike in profiler
-  With this PR observe no spike is happening.

Remove Response and specify the type needed to avoid extra allocation coming from DownloadHandler.Text

---

Runtime/Core/Scripts/Animation/VoiceHandler.cs

-   This changes adds additional checks that would limit reaching memory access out of bounds on WebGL error.
-   Create new project, import example scene
-   add VoiceHandler component
-  set build target to webGL and run the built application
[SRV-1434]: https://ready-player-me.atlassian.net/browse/SRV-1434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SRV-1434 webgl voice handler outofbounds

---

Runtime/Core/Scripts/Animation/VoiceHandler.cs

This should fix issue #323, where for some AudioClip lengths the GetAmplitude method tried to read data from the clip even if the remaining samples were 0.
- add VoiceHandler component on an avatar
- set build target to webGL and run the built application
- let the AudioSource referenced by the VoiceHandler reproduce AudioClips with various lengths

Fix VoiceHandler memory access out of bounds on WebGL

---

README.md
Samples~/AvatarCreatorSamples/AvatarCreatorWizard/Scripts/UI/AssetButtonCreator.cs
Samples~/AvatarCreatorSamples/AvatarCreatorWizard/Scripts/UI/SelectionScreens/AvatarCreatorSelection.cs
Samples~/AvatarCreatorSamples/AvatarCreatorWizard/Scripts/Utils/AssetTypeHelper.cs

-  Fixes https://github.com/readyplayerme/rpm-unity-sdk-core/issues/325. 
-  These changes ensure that equipped colors are now taken into account when loading an avatar, instead of defaulting to the first color.
- Open the AvatarCreatorWizard scene.
- Create a new avatar using the template.
- In the editor, navigate to the skin, eyebrow, hair, or beard category.
- Verify that the displayed color matches what the avatar is currently wearing.
https://github.com/user-attachments/assets/0a8c7992-ed94-4ece-8b66-9cf7bbbf2962
[SRV-1555]: https://ready-player-me.atlassian.net/browse/SRV-1555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(colors): mark avatar's equipped colors as selected

---

Editor/Core/Scripts/UI/EditorWindows/SetupGuide/SetupGuide.cs
Runtime/Core/Scripts/Utils/AvatarAPIParameters.cs
Runtime/Core/Scripts/Utils/AvatarConfigProcessor.cs
Runtime/Core/Scripts/Utils/WebRequestDispatcher.cs

-   This PR updates the handling of avatar config adding  the use of textureFormat=jpeg by default which will ensure correct texture format (no webp support)
- Also now if no blenshapes are set in the config it will be set to none by default to prevent unexpected blendshapes being added

Improve avatar config handling

---

Runtime/AvatarCreator/Scripts/Managers/AvatarManager.cs
Samples~/AvatarCreatorSamples/AvatarCreatorElements/Scripts/AvatarHandler.cs
Samples~/AvatarCreatorSamples/AvatarCreatorWizard/Scripts/Utils/AssetTypeHelper.cs.meta

-   This PR improves how headwear equipping is handled in the Avatar Creator elements 
- ThHis also adds an UpdateAssets function to the Avatar Manager so that you can equip multiple items at once making it easier to unequip the headwear and re-equip the hair at the same time.

Improve handing of headwear equipping

---

Runtime/Core/Scripts/JsonConverters/BodyTypeConverter.cs

Found that the `BodyType.FullBodyXR` was being written as `fullbodyxr` when the API only recognized `fullbody-xr`.
Using `EnumExtensions.GetDescription` appears to fix the issue.

Fix/Update BodyTypeConverter.WriteJson to use EnumExtensions.GetDescription
